<section class="testimonial" id="testimonial">
	<div class="container">
		<header class="header"><h2>Client's Testimonials</h2><p>Showcase what your happy clients say about your services.</p>
		</header>    <div id="slider" class="flexslider">
		<ul class="slides">
			<li style="width: 100%; float: left; margin-right: -100%; position: relative; opacity: 1; display: block; z-index: 2;" class="flex-active-slide">
				<div class="holder">
					<div class="row">
						<div class="img-holder">
							<img width="380" height="481" src="https://raratheme.com/preview/spa-and-salon-pro/wp-content/uploads/2016/11/woman-751236_640-380x481.jpg" class="attachment-spa-and-salon-testmonial size-spa-and-salon-testmonial wp-post-image hoverZoomLink" alt="" data-attachment-id="87" data-permalink="https://raratheme.com/preview/spa-and-salon-pro/alicia-lock/woman-751236_640/" data-orig-file="https://raratheme.com/preview/spa-and-salon-pro/wp-content/uploads/2016/11/woman-751236_640.jpg" data-orig-size="434,640" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;16&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;Canon EOS 5D Mark III&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;0&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;85&quot;,&quot;iso&quot;:&quot;100&quot;,&quot;shutter_speed&quot;:&quot;0.00625&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;0&quot;}" data-image-title="woman-751236_640" data-image-description="" data-medium-file="https://raratheme.com/preview/spa-and-salon-pro/wp-content/uploads/2016/11/woman-751236_640-203x300.jpg" data-large-file="https://raratheme.com/preview/spa-and-salon-pro/wp-content/uploads/2016/11/woman-751236_640.jpg" draggable="false" scale="0">                            
						</div>
						<div class="text-holder">
							<div class="holder mCustomScrollbar _mCS_4 mCS-autoHide mCS_no_scrollbar" style="position: relative; overflow: visible;"><div id="mCSB_4" class="mCustomScrollBox mCS-minimal mCSB_vertical mCSB_outside" style="max-height: none;" tabindex="0"><div id="mCSB_4_container" class="mCSB_container mCS_y_hidden mCS_no_scrollbar_y" style="position:relative; top:0; left:0;" dir="ltr">
								<h3 class="name">Christina Prado</h3>
								<p>I just love it.. would like to come by again thanks!&nbsp;I took a herbal Massage in the Spa and i know i will never be going anywhere else. I am relaxed after my every visit to the Spa. The herbs here smells amazing and provides you the best experience ever!</p>
							</div></div><div id="mCSB_4_scrollbar_vertical" class="mCSB_scrollTools mCSB_4_scrollbar mCS-minimal mCSB_scrollTools_vertical" style="display: none;"><div class="mCSB_draggerContainer"><div id="mCSB_4_dragger_vertical" class="mCSB_dragger" style="position: absolute; min-height: 50px; height: 0px; top: 0px;"><div class="mCSB_dragger_bar" style="line-height: 50px;"></div></div><div class="mCSB_draggerRail"></div></div></div></div>
						</div>    
					</div>
				</div>
			</li>
			<li style="width: 100%; float: left; margin-right: -100%; position: relative; opacity: 0; display: block; z-index: 1;">
				<div class="holder">
					<div class="row">
						<div class="img-holder">
							<img width="380" height="481" src="https://raratheme.com/preview/spa-and-salon-pro/wp-content/uploads/2016/11/adult-21045_640-380x481.jpg" class="attachment-spa-and-salon-testmonial size-spa-and-salon-testmonial wp-post-image hoverZoomLink" alt="" data-attachment-id="112" data-permalink="https://raratheme.com/preview/spa-and-salon-pro/george-donald/adult-21045_640/" data-orig-file="https://raratheme.com/preview/spa-and-salon-pro/wp-content/uploads/2016/11/adult-21045_640.jpg" data-orig-size="426,640" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;16&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;Canon EOS 5D Mark II&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;0&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;105&quot;,&quot;iso&quot;:&quot;100&quot;,&quot;shutter_speed&quot;:&quot;0.00625&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;1&quot;}" data-image-title="adult-21045_640" data-image-description="" data-medium-file="https://raratheme.com/preview/spa-and-salon-pro/wp-content/uploads/2016/11/adult-21045_640-200x300.jpg" data-large-file="https://raratheme.com/preview/spa-and-salon-pro/wp-content/uploads/2016/11/adult-21045_640.jpg" draggable="false" scale="0">                            
						</div>
						<div class="text-holder">
							<div class="holder mCustomScrollbar _mCS_5 mCS-autoHide mCS_no_scrollbar" style="position: relative; overflow: visible;"><div id="mCSB_5" class="mCustomScrollBox mCS-minimal mCSB_vertical mCSB_outside" style="max-height: none;" tabindex="0"><div id="mCSB_5_container" class="mCSB_container mCS_y_hidden mCS_no_scrollbar_y" style="position:relative; top:0; left:0;" dir="ltr">
								<h3 class="name">Betty White</h3>
								<p>I and an avid traveler and trekker. I dont miss to visit this Spa after my every trek and receive their special Trekker’s foot massage. This relieves my muscles and makes my tired legs feel rejuvenated. This is definitely the best massage for tired legs.</p>
							</div></div><div id="mCSB_5_scrollbar_vertical" class="mCSB_scrollTools mCSB_5_scrollbar mCS-minimal mCSB_scrollTools_vertical" style="display: none;"><div class="mCSB_draggerContainer"><div id="mCSB_5_dragger_vertical" class="mCSB_dragger" style="position: absolute; min-height: 50px; height: 0px; top: 0px;"><div class="mCSB_dragger_bar" style="line-height: 50px;"></div></div><div class="mCSB_draggerRail"></div></div></div></div>
						</div>    
					</div>
				</div>
			</li>
			<li style="width: 100%; float: left; margin-right: -100%; position: relative; opacity: 0; display: block; z-index: 1;">
				<div class="holder">
					<div class="row">
						<div class="img-holder">
							<img width="380" height="481" src="https://raratheme.com/preview/spa-and-salon-pro/wp-content/uploads/2016/11/img14-2.jpg" class="attachment-spa-and-salon-testmonial size-spa-and-salon-testmonial wp-post-image" alt="" srcset="https://raratheme.com/preview/spa-and-salon-pro/wp-content/uploads/2016/11/img14-2.jpg 380w, https://raratheme.com/preview/spa-and-salon-pro/wp-content/uploads/2016/11/img14-2-237x300.jpg 237w" sizes="(max-width: 380px) 100vw, 380px" data-attachment-id="138" data-permalink="https://raratheme.com/preview/spa-and-salon-pro/spa-and-massage/img14-3/" data-orig-file="https://raratheme.com/preview/spa-and-salon-pro/wp-content/uploads/2016/11/img14-2.jpg" data-orig-size="380,481" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;0&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;0&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;0&quot;,&quot;iso&quot;:&quot;0&quot;,&quot;shutter_speed&quot;:&quot;0&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;0&quot;}" data-image-title="img14" data-image-description="" data-medium-file="https://raratheme.com/preview/spa-and-salon-pro/wp-content/uploads/2016/11/img14-2-237x300.jpg" data-large-file="https://raratheme.com/preview/spa-and-salon-pro/wp-content/uploads/2016/11/img14-2.jpg" draggable="false">                            
						</div>
						<div class="text-holder">
							<div class="holder mCustomScrollbar _mCS_6 mCS-autoHide mCS_no_scrollbar" style="position: relative; overflow: visible;"><div id="mCSB_6" class="mCustomScrollBox mCS-minimal mCSB_vertical mCSB_outside" style="max-height: none;" tabindex="0"><div id="mCSB_6_container" class="mCSB_container mCS_y_hidden mCS_no_scrollbar_y" style="position:relative; top:0; left:0;" dir="ltr">
								<h3 class="name">Michelle Prado</h3>
								<p>I just love it.. would like to come by again thanks! Tranquility Spa is best for body massage. Every time is get treated here, i get very relaxed and i go happy all day. This is very relaxing and fun. I recommend it to all my friends.</p>
							</div></div><div id="mCSB_6_scrollbar_vertical" class="mCSB_scrollTools mCSB_6_scrollbar mCS-minimal mCSB_scrollTools_vertical" style="display: none;"><div class="mCSB_draggerContainer"><div id="mCSB_6_dragger_vertical" class="mCSB_dragger" style="position: absolute; min-height: 50px; height: 0px; top: 0px;"><div class="mCSB_dragger_bar" style="line-height: 50px;"></div></div><div class="mCSB_draggerRail"></div></div></div></div>
						</div>    
					</div>
				</div>
			</li>
			<li style="width: 100%; float: left; margin-right: -100%; position: relative; opacity: 0; display: block; z-index: 1;">
				<div class="holder">
					<div class="row">
						<div class="img-holder">
							<img width="380" height="481" src="https://raratheme.com/preview/spa-and-salon-pro/wp-content/uploads/2016/11/test-1-380x481.jpg" class="attachment-spa-and-salon-testmonial size-spa-and-salon-testmonial wp-post-image hoverZoomLink" alt="" data-attachment-id="348" data-permalink="https://raratheme.com/preview/spa-and-salon-pro/testimonial/christina-prado/test-1/" data-orig-file="https://raratheme.com/preview/spa-and-salon-pro/wp-content/uploads/2016/11/test-1.jpg" data-orig-size="380,571" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;5.6&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;Canon EOS REBEL T1i&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;0&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;300&quot;,&quot;iso&quot;:&quot;1600&quot;,&quot;shutter_speed&quot;:&quot;0.0005&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;1&quot;}" data-image-title="test-1" data-image-description="" data-medium-file="https://raratheme.com/preview/spa-and-salon-pro/wp-content/uploads/2016/11/test-1-200x300.jpg" data-large-file="https://raratheme.com/preview/spa-and-salon-pro/wp-content/uploads/2016/11/test-1.jpg" draggable="false" scale="0">                            
						</div>
						<div class="text-holder">
							<div class="holder mCustomScrollbar _mCS_7 mCS-autoHide mCS_no_scrollbar" style="position: relative; overflow: visible;"><div id="mCSB_7" class="mCustomScrollBox mCS-minimal mCSB_vertical mCSB_outside" style="max-height: none;" tabindex="0"><div id="mCSB_7_container" class="mCSB_container mCS_y_hidden mCS_no_scrollbar_y" style="position:relative; top:0; left:0;" dir="ltr">
								<h3 class="name">Dave Clais</h3>
								<p>I am so happy with the most relaxing massage, i received here. &nbsp;The Staffs were very friendly and offered me plenty of time and service. They were very caring and knowledgeable. They knew exactly where my pressure points were and did a great day. I feel so light and relaxed that i think i can fly.</p>
							</div></div><div id="mCSB_7_scrollbar_vertical" class="mCSB_scrollTools mCSB_7_scrollbar mCS-minimal mCSB_scrollTools_vertical" style="display: none;"><div class="mCSB_draggerContainer"><div id="mCSB_7_dragger_vertical" class="mCSB_dragger" style="position: absolute; min-height: 50px; height: 0px; top: 0px;"><div class="mCSB_dragger_bar" style="line-height: 50px;"></div></div><div class="mCSB_draggerRail"></div></div></div></div>
						</div>    
					</div>
				</div>
			</li>
		</ul>
		<ul class="flex-direction-nav"><li class="flex-nav-prev"><a class="flex-prev" href="#">Previous</a></li><li class="flex-nav-next"><a class="flex-next" href="#">Next</a></li></ul></div>

		<div id="carousel" class="flexslider">

			<div class="flex-viewport" style="overflow: hidden; position: relative;"><ul class="slides" style="width: 800%; transition-duration: 0s; transform: translate3d(0px, 0px, 0px);">
				<li class="flex-active-slide" style="width: 160px; margin-right: 40px; float: left; display: block;">
					<img width="160" height="160" src="https://raratheme.com/preview/spa-and-salon-pro/wp-content/uploads/2016/11/woman-751236_640-160x160.jpg" class="attachment-spa-and-salon-testmonial-thumb size-spa-and-salon-testmonial-thumb wp-post-image hoverZoomLink" alt="" srcset="https://raratheme.com/preview/spa-and-salon-pro/wp-content/uploads/2016/11/woman-751236_640-160x160.jpg 160w, https://raratheme.com/preview/spa-and-salon-pro/wp-content/uploads/2016/11/woman-751236_640-150x150.jpg 150w, https://raratheme.com/preview/spa-and-salon-pro/wp-content/uploads/2016/11/woman-751236_640-434x437.jpg 434w, https://raratheme.com/preview/spa-and-salon-pro/wp-content/uploads/2016/11/woman-751236_640-65x65.jpg 65w" sizes="(max-width: 160px) 100vw, 160px" data-attachment-id="87" data-permalink="https://raratheme.com/preview/spa-and-salon-pro/alicia-lock/woman-751236_640/" data-orig-file="https://raratheme.com/preview/spa-and-salon-pro/wp-content/uploads/2016/11/woman-751236_640.jpg" data-orig-size="434,640" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;16&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;Canon EOS 5D Mark III&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;0&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;85&quot;,&quot;iso&quot;:&quot;100&quot;,&quot;shutter_speed&quot;:&quot;0.00625&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;0&quot;}" data-image-title="woman-751236_640" data-image-description="" data-medium-file="https://raratheme.com/preview/spa-and-salon-pro/wp-content/uploads/2016/11/woman-751236_640-203x300.jpg" data-large-file="https://raratheme.com/preview/spa-and-salon-pro/wp-content/uploads/2016/11/woman-751236_640.jpg" draggable="false">    		
				</li>

				<li style="width: 160px; margin-right: 40px; float: left; display: block;">
					<img width="160" height="160" src="https://raratheme.com/preview/spa-and-salon-pro/wp-content/uploads/2016/11/adult-21045_640-160x160.jpg" class="attachment-spa-and-salon-testmonial-thumb size-spa-and-salon-testmonial-thumb wp-post-image hoverZoomLink" alt="" srcset="https://raratheme.com/preview/spa-and-salon-pro/wp-content/uploads/2016/11/adult-21045_640-160x160.jpg 160w, https://raratheme.com/preview/spa-and-salon-pro/wp-content/uploads/2016/11/adult-21045_640-150x150.jpg 150w, https://raratheme.com/preview/spa-and-salon-pro/wp-content/uploads/2016/11/adult-21045_640-65x65.jpg 65w" sizes="(max-width: 160px) 100vw, 160px" data-attachment-id="112" data-permalink="https://raratheme.com/preview/spa-and-salon-pro/george-donald/adult-21045_640/" data-orig-file="https://raratheme.com/preview/spa-and-salon-pro/wp-content/uploads/2016/11/adult-21045_640.jpg" data-orig-size="426,640" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;16&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;Canon EOS 5D Mark II&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;0&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;105&quot;,&quot;iso&quot;:&quot;100&quot;,&quot;shutter_speed&quot;:&quot;0.00625&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;1&quot;}" data-image-title="adult-21045_640" data-image-description="" data-medium-file="https://raratheme.com/preview/spa-and-salon-pro/wp-content/uploads/2016/11/adult-21045_640-200x300.jpg" data-large-file="https://raratheme.com/preview/spa-and-salon-pro/wp-content/uploads/2016/11/adult-21045_640.jpg" draggable="false">    		
				</li>

				<li style="width: 160px; margin-right: 40px; float: left; display: block;">
					<img width="160" height="160" src="https://raratheme.com/preview/spa-and-salon-pro/wp-content/uploads/2016/11/img14-2-160x160.jpg" class="attachment-spa-and-salon-testmonial-thumb size-spa-and-salon-testmonial-thumb wp-post-image hoverZoomLink" alt="" srcset="https://raratheme.com/preview/spa-and-salon-pro/wp-content/uploads/2016/11/img14-2-160x160.jpg 160w, https://raratheme.com/preview/spa-and-salon-pro/wp-content/uploads/2016/11/img14-2-150x150.jpg 150w, https://raratheme.com/preview/spa-and-salon-pro/wp-content/uploads/2016/11/img14-2-65x65.jpg 65w" sizes="(max-width: 160px) 100vw, 160px" data-attachment-id="138" data-permalink="https://raratheme.com/preview/spa-and-salon-pro/spa-and-massage/img14-3/" data-orig-file="https://raratheme.com/preview/spa-and-salon-pro/wp-content/uploads/2016/11/img14-2.jpg" data-orig-size="380,481" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;0&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;0&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;0&quot;,&quot;iso&quot;:&quot;0&quot;,&quot;shutter_speed&quot;:&quot;0&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;0&quot;}" data-image-title="img14" data-image-description="" data-medium-file="https://raratheme.com/preview/spa-and-salon-pro/wp-content/uploads/2016/11/img14-2-237x300.jpg" data-large-file="https://raratheme.com/preview/spa-and-salon-pro/wp-content/uploads/2016/11/img14-2.jpg" draggable="false">    		
				</li>

				<li style="width: 160px; margin-right: 40px; float: left; display: block;">
					<img width="160" height="160" src="https://raratheme.com/preview/spa-and-salon-pro/wp-content/uploads/2016/11/test-1-160x160.jpg" class="attachment-spa-and-salon-testmonial-thumb size-spa-and-salon-testmonial-thumb wp-post-image hoverZoomLink" alt="" srcset="https://raratheme.com/preview/spa-and-salon-pro/wp-content/uploads/2016/11/test-1-160x160.jpg 160w, https://raratheme.com/preview/spa-and-salon-pro/wp-content/uploads/2016/11/test-1-150x150.jpg 150w, https://raratheme.com/preview/spa-and-salon-pro/wp-content/uploads/2016/11/test-1-180x180.jpg 180w, https://raratheme.com/preview/spa-and-salon-pro/wp-content/uploads/2016/11/test-1-300x300.jpg 300w, https://raratheme.com/preview/spa-and-salon-pro/wp-content/uploads/2016/11/test-1-65x65.jpg 65w" sizes="(max-width: 160px) 100vw, 160px" data-attachment-id="348" data-permalink="https://raratheme.com/preview/spa-and-salon-pro/testimonial/christina-prado/test-1/" data-orig-file="https://raratheme.com/preview/spa-and-salon-pro/wp-content/uploads/2016/11/test-1.jpg" data-orig-size="380,571" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;5.6&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;Canon EOS REBEL T1i&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;0&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;300&quot;,&quot;iso&quot;:&quot;1600&quot;,&quot;shutter_speed&quot;:&quot;0.0005&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;1&quot;}" data-image-title="test-1" data-image-description="" data-medium-file="https://raratheme.com/preview/spa-and-salon-pro/wp-content/uploads/2016/11/test-1-200x300.jpg" data-large-file="https://raratheme.com/preview/spa-and-salon-pro/wp-content/uploads/2016/11/test-1.jpg" draggable="false">    		
				</li>

			</ul></div><ul class="flex-direction-nav"><li class="flex-nav-prev"><a class="flex-prev flex-disabled" href="#" tabindex="-1">Previous</a></li><li class="flex-nav-next"><a class="flex-next flex-disabled" href="#" tabindex="-1">Next</a></li></ul>
		</div>
	</div>            
</section>