<section class="services" id="services">
    <div class="container">
        <div class="header">
            <div class="left">
                <h2>Our Services</h2><p>We offer various kind of services related to Spa and Massage. </p>
            </div>
            <a href="https://raratheme.com/preview/spa-and-salon-pro/services/" class="btn-green">View All Services</a>
        </div>    
        <div class="row">
            <div class="col" style="height: 273px;">
                <a href="https://raratheme.com/preview/spa-and-salon-pro/service/therapeutic-massage/" class="img-holder">
                    <img width="380" height="225" src="https://raratheme.com/preview/spa-and-salon-pro/wp-content/uploads/2016/11/wellness-285591_1280-380x225.jpg" class="attachment-spa-and-salon-service size-spa-and-salon-service wp-post-image hoverZoomLink" alt="" data-attachment-id="52" data-permalink="https://raratheme.com/preview/spa-and-salon-pro/singing-bowl-therapy/wellness-285591_1280/" data-orig-file="https://raratheme.com/preview/spa-and-salon-pro/wp-content/uploads/2016/11/wellness-285591_1280.jpg" data-orig-size="780,520" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;0&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;0&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;0&quot;,&quot;iso&quot;:&quot;0&quot;,&quot;shutter_speed&quot;:&quot;0&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;0&quot;}" data-image-title="wellness-285591_1280" data-image-description="" data-medium-file="https://raratheme.com/preview/spa-and-salon-pro/wp-content/uploads/2016/11/wellness-285591_1280-300x200.jpg" data-large-file="https://raratheme.com/preview/spa-and-salon-pro/wp-content/uploads/2016/11/wellness-285591_1280.jpg">	
                </a>
                <h3><a href="https://raratheme.com/preview/spa-and-salon-pro/service/therapeutic-massage/"> Singing Bowl Therapy</a></h3>
            </div>
            <div class="col" style="height: 273px;">
                <a href="https://raratheme.com/preview/spa-and-salon-pro/service/warm-bamboo-massage/" class="img-holder">
                    <img width="380" height="225" src="https://raratheme.com/preview/spa-and-salon-pro/wp-content/uploads/2016/11/ser-6-380x225.jpg" class="attachment-spa-and-salon-service size-spa-and-salon-service wp-post-image hoverZoomLink" alt="" data-attachment-id="248" data-permalink="https://raratheme.com/preview/spa-and-salon-pro/service/mind-fit/ser-6/" data-orig-file="https://raratheme.com/preview/spa-and-salon-pro/wp-content/uploads/2016/11/ser-6.jpg" data-orig-size="780,437" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;0&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;0&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;0&quot;,&quot;iso&quot;:&quot;0&quot;,&quot;shutter_speed&quot;:&quot;0&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;0&quot;}" data-image-title="ser-6" data-image-description="" data-medium-file="https://raratheme.com/preview/spa-and-salon-pro/wp-content/uploads/2016/11/ser-6-300x168.jpg" data-large-file="https://raratheme.com/preview/spa-and-salon-pro/wp-content/uploads/2016/11/ser-6.jpg">	
                </a>
                <h3><a href="https://raratheme.com/preview/spa-and-salon-pro/service/warm-bamboo-massage/"> Relaxing Massage</a></h3>
            </div>
            <div class="col" style="height: 273px;">
                <a href="https://raratheme.com/preview/spa-and-salon-pro/service/cranial-sacral-therapy/" class="img-holder">
                    <img width="380" height="225" src="https://raratheme.com/preview/spa-and-salon-pro/wp-content/uploads/2016/11/wellness-1021131_1280-380x225.jpg" class="attachment-spa-and-salon-service size-spa-and-salon-service wp-post-image hoverZoomLink" alt="" data-attachment-id="57" data-permalink="https://raratheme.com/preview/spa-and-salon-pro/korean-special-bath/wellness-1021131_1280/" data-orig-file="https://raratheme.com/preview/spa-and-salon-pro/wp-content/uploads/2016/11/wellness-1021131_1280.jpg" data-orig-size="780,520" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;0&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;0&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;0&quot;,&quot;iso&quot;:&quot;0&quot;,&quot;shutter_speed&quot;:&quot;0&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;0&quot;}" data-image-title="wellness-1021131_1280" data-image-description="" data-medium-file="https://raratheme.com/preview/spa-and-salon-pro/wp-content/uploads/2016/11/wellness-1021131_1280-300x200.jpg" data-large-file="https://raratheme.com/preview/spa-and-salon-pro/wp-content/uploads/2016/11/wellness-1021131_1280.jpg">	
                </a>
                <h3><a href="https://raratheme.com/preview/spa-and-salon-pro/service/cranial-sacral-therapy/"> Korean Special Bath</a></h3>
            </div>
            <div class="col" style="height: 273px;">
                <a href="https://raratheme.com/preview/spa-and-salon-pro/service/cranial-release-technique/" class="img-holder">
                    <img width="380" height="225" src="https://raratheme.com/preview/spa-and-salon-pro/wp-content/uploads/2016/11/lemon-906141_1280-380x225.jpg" class="attachment-spa-and-salon-service size-spa-and-salon-service wp-post-image hoverZoomLink" alt="" data-attachment-id="71" data-permalink="https://raratheme.com/preview/spa-and-salon-pro/herbal-therapy/lemon-906141_1280/" data-orig-file="https://raratheme.com/preview/spa-and-salon-pro/wp-content/uploads/2016/11/lemon-906141_1280.jpg" data-orig-size="800,548" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;0&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;0&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;0&quot;,&quot;iso&quot;:&quot;0&quot;,&quot;shutter_speed&quot;:&quot;0&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;0&quot;}" data-image-title="lemon-906141_1280" data-image-description="" data-medium-file="https://raratheme.com/preview/spa-and-salon-pro/wp-content/uploads/2016/11/lemon-906141_1280-300x206.jpg" data-large-file="https://raratheme.com/preview/spa-and-salon-pro/wp-content/uploads/2016/11/lemon-906141_1280.jpg">	
                </a>
                <h3><a href="https://raratheme.com/preview/spa-and-salon-pro/service/cranial-release-technique/"> Herbal Massage Therapy</a></h3>
            </div>
            <div class="col" style="height: 273px;">
                <a href="https://raratheme.com/preview/spa-and-salon-pro/service/access-bars/" class="img-holder">
                    <img width="380" height="225" src="https://raratheme.com/preview/spa-and-salon-pro/wp-content/uploads/2016/11/toner-906142_1280-380x225.jpg" class="attachment-spa-and-salon-service size-spa-and-salon-service wp-post-image hoverZoomLink" alt="" data-attachment-id="65" data-permalink="https://raratheme.com/preview/spa-and-salon-pro/special-beauty-therapy/toner-906142_1280/" data-orig-file="https://raratheme.com/preview/spa-and-salon-pro/wp-content/uploads/2016/11/toner-906142_1280.jpg" data-orig-size="800,556" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;0&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;0&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;0&quot;,&quot;iso&quot;:&quot;0&quot;,&quot;shutter_speed&quot;:&quot;0&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;0&quot;}" data-image-title="toner-906142_1280" data-image-description="" data-medium-file="https://raratheme.com/preview/spa-and-salon-pro/wp-content/uploads/2016/11/toner-906142_1280-300x209.jpg" data-large-file="https://raratheme.com/preview/spa-and-salon-pro/wp-content/uploads/2016/11/toner-906142_1280.jpg">	
                </a>
                <h3><a href="https://raratheme.com/preview/spa-and-salon-pro/service/access-bars/"> Special Beauty Therapy</a></h3>
            </div>
            <div class="col" style="height: 273px;">
                <a href="https://raratheme.com/preview/spa-and-salon-pro/service/mind-fit/" class="img-holder">
                    <img width="380" height="225" src="https://raratheme.com/preview/spa-and-salon-pro/wp-content/uploads/2016/11/alternative-medicine-1327808_1280-1-380x225.jpg" class="attachment-spa-and-salon-service size-spa-and-salon-service wp-post-image hoverZoomLink" alt="" data-attachment-id="94" data-permalink="https://raratheme.com/preview/spa-and-salon-pro/benefits-from-regular-massage/alternative-medicine-1327808_1280-2/" data-orig-file="https://raratheme.com/preview/spa-and-salon-pro/wp-content/uploads/2016/11/alternative-medicine-1327808_1280-1.jpg" data-orig-size="800,531" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;0&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;0&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;0&quot;,&quot;iso&quot;:&quot;0&quot;,&quot;shutter_speed&quot;:&quot;0&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;0&quot;}" data-image-title="alternative-medicine-1327808_1280" data-image-description="" data-medium-file="https://raratheme.com/preview/spa-and-salon-pro/wp-content/uploads/2016/11/alternative-medicine-1327808_1280-1-300x199.jpg" data-large-file="https://raratheme.com/preview/spa-and-salon-pro/wp-content/uploads/2016/11/alternative-medicine-1327808_1280-1.jpg">	
                </a>
                <h3><a href="https://raratheme.com/preview/spa-and-salon-pro/service/mind-fit/"> Trekker’s Foot Massage</a></h3>
            </div>
        </div>
    </div>            
</section>